version: '3.8'
services:
  front:
    container_name: New-tochiman-front
    build: 
      context: ./front
      dockerfile: .Dockerfile
    working_dir: /front
    ports:
      - 3000:3000
    volumes:
      - ./front:/front
    tty: true
    environment:
      - WATCHPACK_POLLING=true
    command: "yarn dev"
    